name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-build-db:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mrtalon63
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: trackdirect-db.dockerfile
          push: true
          tags: |
            ghcr.io/mrtalon63/trackdirect-db:latest
            ghcr.io/mrtalon63/trackdirect-db:${{ github.RUN_ID }}

  docker-build-apache:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mrtalon63
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: trackdirect-apache.dockerfile
          push: true
          tags: |
            ghcr.io/mrtalon63/trackdirect-apache:latest
            ghcr.io/mrtalon63/trackdirect-apache:${{ github.RUN_ID }}

  docker-build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mrtalon63
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: trackdirect-python.dockerfile
          push: true
          tags: |
            ghcr.io/mrtalon63/trackdirect-python:latest
            ghcr.io/mrtalon63/trackdirect-python:${{ github.RUN_ID }}

  docker-build-aprsc:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mrtalon63
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: trackdirect-aprsc.dockerfile
          push: true
          tags: |
            ghcr.io/mrtalon63/trackdirect-aprsc:latest
            ghcr.io/mrtalon63/trackdirect-aprsc:${{ github.RUN_ID }}

  docker-build-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mrtalon63
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: trackdirect-cron.dockerfile
          push: true
          tags: |
            ghcr.io/mrtalon63/trackdirect-cron:latest
            ghcr.io/mrtalon63/trackdirect-cron:${{ github.RUN_ID }}
